const express=require("express")
const app=express()
const cors=require("cors")
const bodyparser=require("body-parser")
app.use(bodyparser.json())
app.use(cors())
app.use(bodyparser.urlencoded({extended:false}))
const getMethods=require("./routes/getRoutes")
const signup=require("./routes/saveEmployee")
const signin=require("./routes/signinUser")
const findusers=require("./routes/fetchUsers")
const updateuser=require("./routes/updateUser")
const deleteuser=require("./routes/deleteUser")
app.use("/",getMethods)
app.use("/",signup)
app.use("/",signin)
app.use("/",findusers)
app.use("/",updateuser)
app.use("/",deleteuser)
app.listen(3001,()=>console.log("server started"))