const express=require("express")
const app=express()
const bodyparser=require("body-parser")
app.use(bodyparser.json())
app.use(bodyparser.urlencoded({extended:false}))
const getMethods=require("./routes/getRoutes")
const signup=require("./routes/saveEmployee")
const signin=require("./routes/signinUser")
app.use("/",getMethods)
app.use("/",signup)
app.use("/",signin)
app.listen(3000,()=>console.log("server started"))